name: Deploy Azure SQL Database Schema

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute SQL Migration
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './db-migrations/V1__init_audit.sql'
          action: 'run'
